### ISSUE TITLE
Send message undefined 0

### ISSUE THREAD

**Issue by JonoHall** [stormageddon/steam-buddy#8]
Hi there, I hope this project is still active!

Having an issue with the following console output when running:

```
Send message undefined 0

config: { message: '#{player} is playing #{game}.',
  channels: { general: [ 'Jono' ] } }

sending + channel length 0
```

Here is my config:

```
{
  "users": ["DumKopf"],
  "slack": {
    "message": "#{player} is playing #{game}.",
    "channels": {
      "general": ["Jono"]
    }
  }
}
```

**Comment by JonoHall** [comment]
Chased my tail for two days thinking my node version was too recent, figuring out how to wind it back to an earlier version etc. Turned out my bot just wasn't in a channel!

Thanks for the app!

**Comment by stormageddon** [comment]
Holy cow, someone uses this! Glad you figured it out @JonoHall . I wasn't paying attention to this repo because I didn't think anyone used it. Let me know if you need help with anything else!

**Comment by JonoHall** [comment]
Yeah, it was a good chance to have a play around with plugins, node, practice linux stuff. Just a bit of a fun project ;)

Turns out the plugin sends out too many messages saying someone is in game, it'll pop one in the channel, then at an arbitrary time it will send another one (as little as 2 minutes!).

It might be my set up though.

Thanks again for the project @stormageddon. I'd suggest updating the docs to ensure the user has added their bot to a channel to prevent the issue I was having.
